---
title: "Bigrams and Biterm Topic Model (BTM)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Content 

This page was created for providing the code, reproducing the results and presenting the step-by-step process of the results found in the paper: 

> Valença, G.; Hook, H. _Why do some American fear "15-minute cities"?_. Paper currently submitted for revision. 

**1. Code**

The code used for the developing the bigrams and Biterm Topic Models (BTM) can be found at: [code](TopicModelling_bigram.R)

**2. Dataset**

The dataset used in this work is shared only by request. Since we used data from Reddit, there has concerns related to privacy risks. Nonetheless, researchers propose that sharing the dataset upon request is a respectable compromise, balancing the need for reproducibility with ethical considerations. Please contact the authors for the treated dataset with omitted id's. 

**2. Reproducibility of the results**

The step-by-step process and the results are reproduced in this webpage. Please check below:

* [Bigrams](bigram.md)

* [Biterm Topic Model](BTM.md)



